# -*- coding: utf-8 -*-
"""
電子帳簿保存システム - ビルド自動化スクリプト
Build automation script for Denshi Chobo Hozon System

使用方法:
    python build.py [--skip-installer]

オプション:
    --skip-installer : インストーラー作成をスキップしてexe化のみ実行
"""

import os
import sys
import subprocess
import shutil
from pathlib import Path
from VERSION import __version__, __build_date__, APP_NAME_EN

# ビルド設定
PROJECT_ROOT = Path(__file__).parent.absolute()
DIST_DIR = PROJECT_ROOT / "dist"
BUILD_DIR = PROJECT_ROOT / "build"
INSTALLER_DIR = PROJECT_ROOT / "installer"
SPEC_FILE = PROJECT_ROOT / "denshi.spec"

# カラー出力用
class Color:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

def print_header(message):
    """ヘッダーメッセージを出力"""
    print(f"\n{Color.HEADER}{Color.BOLD}{'='*60}{Color.ENDC}")
    print(f"{Color.HEADER}{Color.BOLD}{message}{Color.ENDC}")
    print(f"{Color.HEADER}{Color.BOLD}{'='*60}{Color.ENDC}\n")

def print_success(message):
    """成功メッセージを出力"""
    print(f"{Color.OKGREEN}✓ {message}{Color.ENDC}")

def print_warning(message):
    """警告メッセージを出力"""
    print(f"{Color.WARNING}⚠ {message}{Color.ENDC}")

def print_error(message):
    """エラーメッセージを出力"""
    print(f"{Color.FAIL}✗ {message}{Color.ENDC}")

def print_info(message):
    """情報メッセージを出力"""
    print(f"{Color.OKCYAN}ℹ {message}{Color.ENDC}")

def check_dependencies():
    """必要な依存関係をチェック"""
    print_header("依存関係のチェック")

    # PyInstallerのチェック
    try:
        import PyInstaller
        print_success(f"PyInstaller {PyInstaller.__version__} がインストールされています")
    except ImportError:
        print_error("PyInstallerがインストールされていません")
        print_info("pip install pyinstaller でインストールしてください")
        return False

    # リソースファイルのチェック
    if not (INSTALLER_DIR / "icon.ico").exists():
        print_warning("installer/icon.ico が見つかりません")
        print_info("アイコンなしでビルドを続行します")
    else:
        print_success("icon.ico が見つかりました")

    return True

def create_version_info():
    """Windowsバージョン情報ファイルを生成"""
    print_header("バージョン情報ファイルの生成")

    # バージョン番号を数値形式に変換（例: "v2.0.0" → "2,0,0,0"）
    version_numbers = __version__.lstrip('v').split('.')
    while len(version_numbers) < 4:
        version_numbers.append('0')
    file_version = ','.join(version_numbers)
    product_version = file_version

    version_info_content = f"""# -*- coding: utf-8 -*-
# Auto-generated by build.py - DO NOT EDIT MANUALLY

VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({file_version}),
    prodvers=({product_version}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        u'041104B0',
        [StringStruct(u'CompanyName', u'Your Organization'),
        StringStruct(u'FileDescription', u'電子帳簿保存システム'),
        StringStruct(u'FileVersion', u'{__version__}'),
        StringStruct(u'InternalName', u'{APP_NAME_EN}'),
        StringStruct(u'LegalCopyright', u'Copyright (C) 2025-2026'),
        StringStruct(u'OriginalFilename', u'{APP_NAME_EN}.exe'),
        StringStruct(u'ProductName', u'電子帳簿保存システム'),
        StringStruct(u'ProductVersion', u'{__version__} ({__build_date__})')])
      ]
    ),
    VarFileInfo([VarStruct(u'Translation', [0x411, 1200])])
  ]
)
"""

    version_file = PROJECT_ROOT / "file_version_info.txt"
    with open(version_file, 'w', encoding='utf-8') as f:
        f.write(version_info_content)

    print_success(f"file_version_info.txt を生成しました（バージョン: {__version__}）")
    return True

def clean_build_directories():
    """前回のビルド成果物をクリーンアップ"""
    print_header("前回のビルド成果物のクリーンアップ")

    for directory in [BUILD_DIR, DIST_DIR]:
        if directory.exists():
            print_info(f"{directory.name}/ を削除しています...")
            shutil.rmtree(directory)
            print_success(f"{directory.name}/ を削除しました")
        else:
            print_info(f"{directory.name}/ は存在しません（スキップ）")

def run_pyinstaller():
    """PyInstallerを実行してexeを生成"""
    print_header("PyInstallerの実行")

    if not SPEC_FILE.exists():
        print_error(f"{SPEC_FILE.name} が見つかりません")
        return False

    print_info(f"specファイル: {SPEC_FILE}")
    print_info(f"バージョン: {__version__}")
    print_info(f"ビルド日: {__build_date__}")
    print_info("PyInstallerを実行しています...\n")

    try:
        result = subprocess.run(
            ["pyinstaller", "--clean", str(SPEC_FILE)],
            check=True,
            cwd=PROJECT_ROOT
        )
        print_success("PyInstallerの実行が完了しました")
        return True
    except subprocess.CalledProcessError as e:
        print_error(f"PyInstallerの実行に失敗しました: {e}")
        return False
    except FileNotFoundError:
        print_error("pyinstallerコマンドが見つかりません")
        print_info("pip install pyinstaller でインストールしてください")
        return False

def verify_exe():
    """生成されたexeファイルを確認"""
    print_header("生成されたexeファイルの確認")

    exe_dir = DIST_DIR / APP_NAME_EN
    exe_file = exe_dir / f"{APP_NAME_EN}.exe"

    if not exe_file.exists():
        print_error(f"exeファイルが見つかりません: {exe_file}")
        return False

    file_size = exe_file.stat().st_size / (1024 * 1024)  # MB単位
    print_success(f"exeファイルを確認しました: {exe_file.name}")
    print_info(f"ファイルサイズ: {file_size:.2f} MB")
    print_info(f"出力ディレクトリ: {exe_dir}")

    return True

def create_installer():
    """Inno Setupでインストーラーを作成"""
    print_header("インストーラーの作成")

    iss_file = INSTALLER_DIR / "denshi.iss"

    if not iss_file.exists():
        print_warning(f"{iss_file} が見つかりません")
        print_info("インストーラー作成をスキップします")
        return True  # インストーラーなしでも成功とみなす

    # Inno Setup Compilerのパスを検索
    iscc_paths = [
        r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
        r"C:\Program Files\Inno Setup 6\ISCC.exe",
        r"C:\Program Files (x86)\Inno Setup 5\ISCC.exe",
        r"C:\Program Files\Inno Setup 5\ISCC.exe",
    ]

    iscc_exe = None
    for path in iscc_paths:
        if Path(path).exists():
            iscc_exe = path
            break

    if not iscc_exe:
        print_warning("Inno Setup Compilerが見つかりません")
        print_info("https://jrsoftware.org/isdl.php からダウンロードしてインストールしてください")
        print_info("インストーラー作成をスキップします")
        return True  # インストーラーなしでも成功とみなす

    print_info(f"Inno Setup Compiler: {iscc_exe}")
    print_info("インストーラーを作成しています...\n")

    try:
        result = subprocess.run(
            [iscc_exe, str(iss_file)],
            check=True,
            cwd=PROJECT_ROOT
        )
        print_success("インストーラーの作成が完了しました")

        # 生成されたインストーラーを確認
        installer_output = INSTALLER_DIR / "Output" / f"{APP_NAME_EN}_{__version__}_setup.exe"
        if installer_output.exists():
            file_size = installer_output.stat().st_size / (1024 * 1024)  # MB単位
            print_success(f"インストーラーファイル: {installer_output.name}")
            print_info(f"ファイルサイズ: {file_size:.2f} MB")

        return True
    except subprocess.CalledProcessError as e:
        print_error(f"インストーラーの作成に失敗しました: {e}")
        return False

def main():
    """メイン処理"""
    print_header(f"電子帳簿保存システム ビルドスクリプト v{__version__}")

    # コマンドライン引数の処理
    skip_installer = "--skip-installer" in sys.argv

    # 依存関係のチェック
    if not check_dependencies():
        print_error("依存関係のチェックに失敗しました")
        return 1

    # バージョン情報ファイルの生成
    if not create_version_info():
        print_error("バージョン情報ファイルの生成に失敗しました")
        return 1

    # クリーンアップ
    clean_build_directories()

    # PyInstallerの実行
    if not run_pyinstaller():
        print_error("PyInstallerの実行に失敗しました")
        return 1

    # exeファイルの確認
    if not verify_exe():
        print_error("exeファイルの確認に失敗しました")
        return 1

    # インストーラーの作成
    if not skip_installer:
        if not create_installer():
            print_warning("インストーラーの作成に失敗しましたが、exe化は成功しています")
    else:
        print_info("--skip-installer オプションが指定されているため、インストーラー作成をスキップします")

    # 完了メッセージ
    print_header("ビルド完了")
    print_success(f"バージョン {__version__} のビルドが完了しました")
    print_info(f"出力ディレクトリ: {DIST_DIR / APP_NAME_EN}")

    return 0

if __name__ == "__main__":
    sys.exit(main())
